# Generated by Django 5.0.6 on 2024-09-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('الاسم', models.CharField(max_length=100)),
                ('الموعد', models.DecimalField(decimal_places=2, max_digits=10)),
                ('الهاتف', models.TextField()),
                ('الاقامة', models.TextField()),
                ('الايصال', models.ImageField(upload_to='photos/Xy/Xm/%d')),
                ('القسم', models.CharField(choices=[('option1', 'القسم الأول'), ('option2', 'القسم الثاني'), ('option3', 'القسم الثالث')], default='option1', max_length=20)),
                ('نشط', models.BooleanField(default=True)),
            ],
        ),
    ]
