# Generated by Django 5.0.6 on 2024-09-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='الموعد',
            field=models.IntegerField(),
        ),
    ]
