# Generated by Django 5.0.6 on 2024-09-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_الاقامة_alter_client_القسم_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='الهاتف',
            field=models.CharField(max_length=12),
        ),
    ]
