# Generated by Django 5.0.6 on 2024-09-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_الهاتف'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='الاقامة',
            field=models.CharField(max_length=12),
        ),
    ]
